build: Update .travis.yml for ppc64le support (#179)
* Update .travis.yml for ppc64le support

Add ppc64le support

* Update .travis.yml

* Update .travis.yml

* Address review comments

* Address review comments for docker build and tag.

* Address review comments for github and npm releases

* Fix "the input device is not a TTY" message on ppc64le

"docker -it" flag is not supported on lxd container environment on travis.

* Run image build on amd & ppc parallelly

* Fix permission denied error for docker manifest

Error: open /etc/docker/certs.d/quay.io: permission denied

* Fix addition of apt install output to release artifact.

"sudo apt-get install -y gettext-base" adds following output to resources.yaml file

Reading package lists...
Building dependency tree...
Reading state information...
gettext-base is already the newest version (0.19.7-2ubuntu3.1).
0 upgraded, 0 newly installed, 0 to remove and 28 not upgraded.
apiVersion: v1

* Fix docker push command for manifest.

Error:
The push refers to repository [quay.io/razee/remoteresources3]
An image does not exist locally with the tag: quay.io/razee/remoteresources3

Co-authored-by: Alex Lewitt <48691328+alewitt2@users.noreply.github.com>
Co-authored-by: Siddhesh Ghadi <61187612+Siddhesh-Ghadi@users.noreply.github.com>
Co-authored-by: Siddhesh Ghadi <Siddhesh.Ghadi@ibm.com>